/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Fw9nqMdCdKQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"

export default function generatePage() {
  return (
    <div className="min-h-screen p-4 space-y-4">
      <header className="flex items-center justify-between p-4 border-b">
        <h1 className="text-xl font-bold">Generate & Edit</h1>
        <div className="flex items-center space-x-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">Load a saved persona...</Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem>Persona 1</DropdownMenuItem>
              <DropdownMenuItem>Persona 2</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <Button>Save Progress</Button>
          <Button variant="outline">Download Image</Button>
        </div>
      </header>
      <main className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div>
          <Card className="space-y-4">
            <CardContent>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Customize Persona" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="persona1">Persona 1</SelectItem>
                  <SelectItem value="persona2">Persona 2</SelectItem>
                </SelectContent>
              </Select>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Documents" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="doc1">Document 1</SelectItem>
                  <SelectItem value="doc2">Document 2</SelectItem>
                </SelectContent>
              </Select>
              <Textarea placeholder="Add Content" className="w-full" defaultValue="We is going to the market." />
              <Button className="w-full">Submit</Button>
            </CardContent>
          </Card>
        </div>
        <div>
          <ScrollArea className="h-[calc(100vh-8rem)]">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Alice Vuong</CardTitle>
                    <CardDescription>
                      Exceptionally driven, resilient, and adaptable military spouse with 2+ years of experience in
                      household project management, team leadership, and process improvement.
                    </CardDescription>
                  </CardHeader>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Goals</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <Badge className="mr-2 mb-2">Become a lead project manager</Badge>
                    <Badge className="mr-2 mb-2">Goal 2</Badge>
                    <Badge className="mr-2 mb-2">Goal 3</Badge>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Life Experiences</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <Badge className="mr-2 mb-2">Navigates Dynamic Army Environments</Badge>
                    <Badge className="mr-2 mb-2">Independently Manages Household</Badge>
                    <Badge className="mr-2 mb-2">Adapts to Unpredictable Situations</Badge>
                    <Badge className="mr-2 mb-2">Quickly Builds Strong Relationships</Badge>
                  </CardContent>
                </Card>
              </div>
              <div className="space-y-4">
                <Card>
                  <CardHeader>
                    <CardTitle>Qualifications and Education</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <Badge className="mr-2 mb-2">2+ Years Project Management</Badge>
                    <Badge className="mr-2 mb-2">Qualification 2</Badge>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Skills</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <Badge className="mr-2 mb-2">Financial Management</Badge>
                    <Badge className="mr-2 mb-2">Time and Resource Management</Badge>
                    <Badge className="mr-2 mb-2">Skill 3</Badge>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Strengths</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <Badge className="mr-2 mb-2">Excellence</Badge>
                    <Badge className="mr-2 mb-2">Adaptability</Badge>
                    <Badge className="mr-2 mb-2">Resilience</Badge>
                    <Badge className="mr-2 mb-2">Innovation</Badge>
                    <Badge className="mr-2 mb-2">Accountability</Badge>
                    <Badge className="mr-2 mb-2">Teamwork</Badge>
                  </CardContent>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Value Proposition</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <Badge className="mr-2 mb-2">Robust Army Community Connections</Badge>
                    <Badge className="mr-2 mb-2">Interest in Long-Term Employment</Badge>
                    <Badge className="mr-2 mb-2">Diverse Perspectives and Knowledge</Badge>
                  </CardContent>
                </Card>
              </div>
            </div>
          </ScrollArea>
        </div>
      </main>
    </div>
  )
}
