/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xICZiGL9AUl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Badge } from "@/components/ui/badge"

export function TCard() {
  return (
      <div className="p-6 bg-gray-900 rounded-md text-white space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-gray-800 p-6 rounded-md">
          <h2 className="text-xl font-bold">Alice Vuong</h2>
          <p className="mt-2">
            Driven and adaptable military spouse with a proven record in leading household project management, team
            dynamics, and process optimization.
          </p>
        </div>
        <div className="bg-gray-800 p-6 rounded-md">
          <h3 className="text-lg font-semibold">Qualifications and Education</h3>
          <div className="mt-2 space-y-2">
            <Badge variant="default">2+ years project management</Badge>
            <Badge variant="default">Project management certification</Badge>
            <Badge variant="default">High school diploma</Badge>
          </div>
        </div>
        <div className="bg-gray-800 p-6 rounded-md">
          <h3 className="text-lg font-semibold">Goals</h3>
          <div className="mt-2 space-y-2">
            <Badge variant="default">Become a lead project manager</Badge>
            <Badge variant="default">Remote or flexible opportunities</Badge>
          </div>
        </div>
        <div className="bg-gray-800 p-6 rounded-md">
          <h3 className="text-lg font-semibold">Skills</h3>
          <div className="mt-2 space-y-2">
            <Badge variant="default">Financial and resource management</Badge>
            <Badge variant="default">Adept at optimizing time and tasks</Badge>
            <Badge variant="default">Logistical planning</Badge>
          </div>
        </div>
        <div className="bg-gray-800 p-6 rounded-md">
          <h3 className="text-lg font-semibold">Life Experiences</h3>
          <div className="mt-2 space-y-2">
            <Badge variant="default">Thrives in dynamic military settings</Badge>
            <Badge variant="default">Manages complex household operations</Badge>
            <Badge variant="default">Adapts to unpredictable challenges</Badge>
            <Badge variant="default">Quickly builds robust relationships</Badge>
            <Badge variant="default">Actively volunteers in community</Badge>
            <Badge variant="default">Provides leadership and mentorship</Badge>
          </div>
        </div>
        <div className="bg-gray-800 p-6 rounded-md">
          <h3 className="text-lg font-semibold">Strengths</h3>
          <div className="mt-2 space-y-2">
            <Badge variant="default">Excellence</Badge>
            <Badge variant="default">Adaptability</Badge>
            <Badge variant="default">Resilience</Badge>
            <Badge variant="default">Innovation</Badge>
            <Badge variant="default">Accountability</Badge>
            <Badge variant="default">Teamwork</Badge>
          </div>
        </div>
        <div className="bg-gray-800 p-6 rounded-md">
          <h3 className="text-lg font-semibold">Value Proposition</h3>
          <div className="mt-2 space-y-2">
            <Badge variant="default">Leverages deep military connections</Badge>
            <Badge variant="default">Committed to long-term employment</Badge>
            <Badge variant="default">Diverse perspectives and expertise</Badge>
          </div>
        </div>
      </div>
    </div>
  )
}
